version: '2'
services:
  database:
    image: mysql:latest
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: test
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: contactdb
  tomcat:
    image: codefreshio/tomcat
    ports:
      - 8090
    links:
      - app
    volumes_from:
      - app
  app:
    image: condo/condominuim:master
    volumes:
      - wars:/opt/tomcat/webapps
    links:
      - database
volumes:
  wars:
    driver: local
